import React, { useMemo, useState } from 'react';
import { X, Plus, Trash2, Link2, WalletCards, FileText, ChevronRight } from 'lucide-react';
import { Appointment, Client, CommercialClosing, PaymentRecord } from '../types';
import { closingSubtotal, closingTotal } from '../utils/commercialClosings';
import { formatCurrencyBRL, formatDateBR } from '../utils/date';

interface Props { closing: CommercialClosing; client: Client; appointments: Appointment[]; onSave:(c:CommercialClosing)=>void; onClose:()=>void; }
export const CommercialClosingModal:React.FC<Props>=({closing,client,appointments,onSave,onClose})=>{
 const [draft,setDraft]=useState<CommercialClosing>(closing); const [extraDesc,setExtraDesc]=useState(''); const [extraValue,setExtraValue]=useState(''); const [payValue,setPayValue]=useState('');
 const clientOS=useMemo(()=>appointments.filter(a=>a.clientId===client.id && a.serviceOrder),[appointments,client.id]);
 const subtotal=closingSubtotal(draft,appointments), total=closingTotal(draft,appointments), received=draft.payments.reduce((s,p)=>s+(p.amount||0),0), balance=Math.max(0,total-received);
 const toggleOS=(id:string)=>setDraft(d=>({...d,appointmentIds:d.appointmentIds.includes(id)?d.appointmentIds.filter(x=>x!==id):[...d.appointmentIds,id],updatedAt:new Date().toISOString()}));
 return <div className="fixed inset-0 z-[80] bg-black/90 backdrop-blur-sm overflow-y-auto p-3"><div className="max-w-2xl mx-auto my-4 bg-zinc-950 border border-zinc-800 rounded-3xl overflow-hidden shadow-2xl">
  <div className="p-4 bg-gradient-to-r from-zinc-950 via-cyan-950/50 to-zinc-950 border-b border-cyan-900/50 flex justify-between"><div><div className="text-[10px] text-cyan-400 font-bold tracking-widest">FECHAMENTO DO SERVIÇO</div><div className="text-xl font-black text-white">{draft.id}</div><div className="text-xs text-zinc-400">{client.name} • controle interno</div></div><button onClick={onClose}><X className="text-zinc-400"/></button></div>
  <div className="p-4 space-y-4">
   <div className="p-3 rounded-2xl bg-zinc-900 border border-zinc-800"><div className="flex items-center gap-2 font-bold text-white mb-2"><Link2 className="w-4 h-4 text-cyan-400"/>OS vinculadas</div><div className="text-xs text-zinc-500 mb-3">Uma OS continua independente. Aqui você apenas reúne os atendimentos que fazem parte do mesmo acordo comercial.</div>{clientOS.length===0?<div className="text-sm text-zinc-500">Nenhuma OS encontrada.</div>:clientOS.map(a=><button key={a.id} onClick={()=>toggleOS(a.id)} className={`w-full mb-2 p-3 rounded-xl border text-left ${draft.appointmentIds.includes(a.id)?'border-cyan-500 bg-cyan-950/30':'border-zinc-800 bg-zinc-950'}`}><div className="flex justify-between gap-2"><div><b className="text-white">{a.serviceOrder}</b><div className="text-xs text-zinc-400">{formatDateBR(a.date)} • {a.serviceTypeName}</div><div className="text-[11px] text-zinc-500">{(a.equipment||[]).map(e=>e.serialNumber).filter(Boolean).join(' • ') || a.serialNumber || 'sem MA'}</div></div><div className="text-cyan-300 font-bold">{formatCurrencyBRL(a.price||0)}</div></div></button>)}</div>
   <div className="p-3 rounded-2xl bg-zinc-900 border border-zinc-800"><div className="font-bold text-white mb-2">Serviços / valores extras</div>{draft.extraItems.map(x=><div key={x.id} className="flex justify-between items-center py-2 border-b border-zinc-800"><span className="text-sm text-zinc-300">{x.description}</span><div className="flex gap-2 items-center"><b className="text-white">{formatCurrencyBRL(x.amount)}</b><button onClick={()=>setDraft(d=>({...d,extraItems:d.extraItems.filter(i=>i.id!==x.id)}))}><Trash2 className="w-4 h-4 text-red-400"/></button></div></div>)}<div className="grid grid-cols-[1fr_110px_40px] gap-2 mt-3"><input value={extraDesc} onChange={e=>setExtraDesc(e.target.value)} placeholder="Ex.: configuração extra" className="bg-zinc-950 border border-zinc-700 rounded-xl px-3 py-2 text-white"/><input type="number" value={extraValue} onChange={e=>setExtraValue(e.target.value)} placeholder="R$" className="bg-zinc-950 border border-zinc-700 rounded-xl px-2 py-2 text-white"/><button onClick={()=>{const v=Number(extraValue);if(!extraDesc.trim()||!v)return;setDraft(d=>({...d,extraItems:[...d.extraItems,{id:`extra-${Date.now()}`,description:extraDesc.trim(),amount:v}]}));setExtraDesc('');setExtraValue('')}} className="rounded-xl bg-cyan-500 text-black"><Plus className="mx-auto"/></button></div></div>
   <div className="p-3 rounded-2xl bg-zinc-900 border border-zinc-800"><div className="font-bold text-white mb-2">Desconto do fechamento</div><div className="grid grid-cols-2 gap-2"><select value={draft.discountType} onChange={e=>setDraft(d=>({...d,discountType:e.target.value as any}))} className="bg-zinc-950 border border-zinc-700 rounded-xl p-2 text-white"><option value="valor">Valor (R$)</option><option value="percentual">Percentual (%)</option></select><input type="number" min="0" value={draft.discountValue} onChange={e=>setDraft(d=>({...d,discountValue:Number(e.target.value)||0}))} className="bg-zinc-950 border border-zinc-700 rounded-xl p-2 text-white"/></div></div>
   <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-center"><div className="p-2 bg-zinc-900 rounded-xl"><small className="text-zinc-500">SUBTOTAL</small><b className="block text-white">{formatCurrencyBRL(subtotal)}</b></div><div className="p-2 bg-zinc-900 rounded-xl"><small className="text-zinc-500">TOTAL</small><b className="block text-white">{formatCurrencyBRL(total)}</b></div><div className="p-2 bg-zinc-900 rounded-xl"><small className="text-zinc-500">RECEBIDO</small><b className="block text-emerald-400">{formatCurrencyBRL(received)}</b></div><div className="p-2 bg-zinc-900 rounded-xl"><small className="text-zinc-500">SALDO</small><b className="block text-amber-300">{formatCurrencyBRL(balance)}</b></div></div>
   <div className="p-3 rounded-2xl bg-zinc-900 border border-zinc-800"><div className="flex items-center gap-2 font-bold text-white mb-2"><WalletCards className="w-4 h-4 text-emerald-400"/>Pagamentos do fechamento</div>{draft.payments.map(p=><div key={p.id} className="flex justify-between py-2 border-b border-zinc-800 text-sm"><span className="text-zinc-400">{formatDateBR(p.date)} • {p.kind==='sinal'?'Sinal':p.kind==='pagamento_final'?'Pagamento final':'Pagamento'}</span><span className="text-emerald-400 font-bold">{formatCurrencyBRL(p.amount)}</span></div>)}<div className="flex gap-2 mt-3"><input type="number" value={payValue} onChange={e=>setPayValue(e.target.value)} placeholder="Valor recebido" className="flex-1 bg-zinc-950 border border-zinc-700 rounded-xl px-3 py-2 text-white"/><button onClick={()=>{const v=Number(payValue);if(!v)return;const p:PaymentRecord={id:`pay-${Date.now()}`,amount:v,method:'pix',kind:received===0?'sinal':'pagamento',date:new Date().toISOString().slice(0,10),createdAt:new Date().toISOString()};setDraft(d=>({...d,payments:[...d.payments,p]}));setPayValue('')}} className="px-3 rounded-xl bg-emerald-500 text-black font-bold">+ Pix</button></div></div>
   <div className="p-3 rounded-2xl border border-amber-900/40 bg-amber-950/20 text-xs text-amber-200"><b>Regra de segurança:</b> este fechamento é uma camada interna do app. Vincular ou retirar uma OS aqui não altera MA, QR, OS oficial, Drive, fotos, garantia ou planilhas.</div>
   <div className="flex gap-2"><button onClick={onClose} className="flex-1 py-3 rounded-xl bg-zinc-900 text-zinc-300">Cancelar</button><button onClick={()=>onSave({...draft,status:balance<=0.009?'finalizado':'em_andamento',updatedAt:new Date().toISOString()})} className="flex-[2] py-3 rounded-xl bg-cyan-500 text-black font-black">Salvar fechamento</button></div>
  </div></div></div>
}
